{
 "title": "time log example",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    UNIX_TIMESTAMP(start_time) * 1000 AS time,\n    SUM(TIMESTAMPDIFF(MINUTE, start_time, end_time)) AS value\nFROM time_stream\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "User 1 Minute per month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \nDATE_FORMAT(start_time, '%Y-%m') AS month, SUM(TIMESTAMPDIFF(MINUTE, start_time, end_time)) AS total_hours\nFROM time_stream\nWHERE user_id = 1\nGROUP BY month\nORDER BY month"
    }
   ]
  },
  {
   "title": "count records",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT \n  count(id) as records\nFROM app.time_stream\n\n"
    }
   ]
  },
  {
   "title": "Count Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  user_id as metric\nFROM app.time_stream\nGROUP BY user_id\n"
    }
   ]
  }
 ]
}